<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a target = '_blank' href =addCustomer.png>Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven" duration-ms="3047" started-at="2020-04-18T18:24:27 IST" finished-at="2020-04-18T18:24:30 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="3047" started-at="2020-04-18T18:24:27 IST" finished-at="2020-04-18T18:24:30 IST">
      <class name="com.w2a.DataDrivenFramework.testCases.BankManagerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.DataDrivenFramework.testCases.BankManagerLoginTest@130e116b]" name="setUp" is-config="true" duration-ms="14138" started-at="2020-04-18T18:24:13 IST" finished-at="2020-04-18T18:24:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:com.w2a.DataDrivenFramework.testCases.BankManagerLoginTest@130e116b]" name="loginAsBankManager" duration-ms="419" started-at="2020-04-18T18:24:27 IST" finished-at="2020-04-18T18:24:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
        <test-method status="PASS" signature="testDown()[pri:0, instance:com.w2a.DataDrivenFramework.testCases.BankManagerLoginTest@130e116b]" name="testDown" is-config="true" duration-ms="675" started-at="2020-04-18T18:24:30 IST" finished-at="2020-04-18T18:24:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDown -->
      </class> <!-- com.w2a.DataDrivenFramework.testCases.BankManagerLoginTest -->
      <class name="com.w2a.DataDrivenFramework.testCases.AddCustomerTest">
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.DataDrivenFramework.testCases.AddCustomerTest@e383572]" name="addCustomer" duration-ms="953" started-at="2020-04-18T18:24:28 IST" data-provider="getData" finished-at="2020-04-18T18:24:29 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lavendra]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rajput]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[246761.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at com.w2a.DataDrivenFramework.testCases.AddCustomerTest.addCustomer(AddCustomerTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target = '_blank' href =addCustomer.png>Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- com.w2a.DataDrivenFramework.testCases.AddCustomerTest -->
    </test> <!-- Test -->
  </suite> <!-- Data Driven -->
</testng-results>
